/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Guis;

import PersonaCliente.Cliente;
import PersonaCliente.ClienteArrayList;
import Reservas.Reserva;
import Reservas.ReservasQueue;
import Utils.UtilDate;
import Utils.UtilGui;
import Vehiculos.VehiculoHashMap;
import Vehiculos.Vehiculo;
import Vehiculos.EnumEstado;
import java.time.LocalDate;
/**
 *
 * @author Braya
 */
public class FrmGestionReservas extends javax.swing.JInternalFrame {
    private ClienteArrayList clientes;
    private VehiculoHashMap vehiculos;
    private ReservasQueue reservas;
    private Reserva reserva;
    /**
     * Creates new form Gestion_Reservas
     */
    public FrmGestionReservas() {
        initComponents();
        this.setClosable(true);      // Activa la "X" para cerrar
        this.setResizable(false);
        this.setIconifiable(true);
        reservas = ReservasQueue.getInstance();
        vehiculos = VehiculoHashMap.getInstance();
        clientes =  ClienteArrayList.getInstance();
    }
    

    private boolean estaDisponible(String placa, LocalDate inicio, LocalDate fin) {
        for (Reserva r : reservas.getQueue()) {
            if (r.getPlacaVehiculo().equals(placa) && r.hayConflictoDeFecha(inicio, fin)) {
                return false;
            }
        }
        return true;
    }
    
    private void mostrarDatos() {
        txtCliente.setText(reserva.getCedulaCliente());
        txtFechaFin.setText(UtilDate.toString(reserva.getFechaFin()));
        txtFechaInicio.setText(UtilDate.toString(reserva.getFechaInicio()));
        txtVehiculo.setText(reserva.getPlacaVehiculo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtFechaFin = new javax.swing.JFormattedTextField();
        txtFechaInicio = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtVehiculo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gestion De Reservas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 530, -1));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtFechaFin.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        txtFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaFinActionPerformed(evt);
            }
        });
        jPanel1.add(txtFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 160, 40));

        txtFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtFechaInicio.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jPanel1.add(txtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 166, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha de Fin");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 160, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha de Inicio");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 166, -1));

        txtCliente.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 160, 40));

        txtVehiculo.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jPanel1.add(txtVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vehiculo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 150, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cliente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 160, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fechaInicio.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 60, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fechaFin.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 70, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vehiculo.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 100, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 60, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 500, 210));

        jPanel2.setOpaque(false);

        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/confirmar.png"))); // NOI18N
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar.png"))); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCrear.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 550, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        if (txtCliente.getText().isBlank() || txtFechaInicio.getText().isBlank() || txtFechaFin.getText().isBlank() || txtVehiculo.getText().isBlank()) {
            UtilGui.enseñarMensaje(rootPane, "Faltan Datos", "Error");
            return;
        }

        if (clientes.find(txtCliente.getText()) == null) {
            UtilGui.enseñarMensaje(rootPane,"Cliente no registrado"," Error");
             return;
        }
        if (UtilDate.formatoFecha(txtFechaInicio.getText()).isBefore(LocalDate.now())) {
            UtilGui.enseñarMensaje(rootPane, "La fecha de inicio no puede ser menor a la actual","Error") ;
             return;
        }
        if (UtilDate.formatoFecha(txtFechaFin.getText()).isBefore(UtilDate.formatoFecha(txtFechaInicio.getText()))) {
             UtilGui.enseñarMensaje(rootPane," La fecha de finalización debe ser posterior a la de inicio", "Error") ;
              return;
        }
        if (UtilDate.formatoFecha(txtFechaInicio.getText()).plusDays(30).isBefore(UtilDate.formatoFecha(txtFechaFin.getText()))) {
            UtilGui.enseñarMensaje(rootPane," No se permiten reservas mayores a 30 días", "Error") ;
            return;
        }
        if (vehiculos.find(txtVehiculo.getText()) == null) {
            UtilGui.enseñarMensaje(rootPane,"Vehiculo no registrado"," Error");
             return;
        }
        
        Boolean disponible = estaDisponible(txtVehiculo.getText(),UtilDate.formatoFecha(txtFechaInicio.getText()),UtilDate.formatoFecha(txtFechaFin.getText()));
        
        if (disponible == false) {
           UtilGui.enseñarMensaje(rootPane,"️ El vehiculo seleccionado no esta disponible", "Error")  ;
           return;
        }

        Reserva nueva = new Reserva(txtCliente.getText() ,txtVehiculo.getText() , UtilDate.formatoFecha(txtFechaInicio.getText()) , UtilDate.formatoFecha(txtFechaFin.getText()));
        Vehiculo resultado = vehiculos.find(txtVehiculo.getText());
        resultado.setEstado(EnumEstado.Alquilado);

        reservas.add(nueva);        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (txtCliente.getText().isBlank() || txtFechaInicio.getText().isBlank() || txtFechaFin.getText().isBlank() || txtVehiculo.getText().isBlank()) {
            UtilGui.enseñarMensaje(rootPane, "Faltan Datos", "Error");
            return;
        }
        for (Reserva r : reservas.getQueue()) {
           r.confirmar();
       }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       boolean modificada = false;

    if (txtCliente.getText().isBlank() || txtFechaInicio.getText().isBlank() ||
        txtFechaFin.getText().isBlank() || txtVehiculo.getText().isBlank()) {
        UtilGui.enseñarMensaje(rootPane, "Faltan Datos", "Error");
        return;
    }

    String cedula = txtCliente.getText();
    String nuevaPlaca = txtVehiculo.getText();

    for (Reserva r : reservas.getQueue()) {
            if (r.getCedulaCliente().equals(cedula) && !r.isConfirmada()) {
                Vehiculo nuevoVehiculo = vehiculos.find(nuevaPlaca);
                if (nuevoVehiculo == null) {
                    UtilGui.enseñarMensaje(rootPane, "Vehículo no registrado", "Error");
                    return;
                }

                if (nuevoVehiculo.getEstado() != EnumEstado.Disponible) {
                    UtilGui.enseñarMensaje(rootPane, "Vehículo no disponible", "Error");
                    return;
                }

                if (!estaDisponible(nuevaPlaca, r.getFechaInicio(), r.getFechaFin())) {
                    UtilGui.enseñarMensaje(rootPane, "Vehículo ocupado en ese rango de fechas", "Error");
                    return;
                }

                Vehiculo anteriorVehiculo = vehiculos.find(r.getPlacaVehiculo());
                if (anteriorVehiculo != null) {
                    anteriorVehiculo.setEstado(EnumEstado.Disponible);
                }

                r.setPlacaVehiculo(nuevaPlaca);
                nuevoVehiculo.setEstado(EnumEstado.Alquilado);

                UtilGui.enseñarMensaje(rootPane, "Reserva modificada", "Info");
                modificada = true;
                break;
            }
           if (!modificada) {
            UtilGui.enseñarMensaje(rootPane, "Reserva no encontrada o ya confirmada", "Error");
           }


        }

       

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       if (txtCliente.getText().isBlank() || txtFechaInicio.getText().isBlank() || txtFechaFin.getText().isBlank() || txtVehiculo.getText().isBlank()) {
            UtilGui.enseñarMensaje(rootPane, "Faltan Datos", "Error");
            return;
        }
        for (Reserva r : reservas.getQueue()) {
           if (r.getCedulaCliente().equals(txtCliente.getText()) && r.getPlacaVehiculo().equals(txtVehiculo.getText())) {
            Vehiculo v = vehiculos.find(txtVehiculo.getText());
            if (v != null) {
                v.setEstado(EnumEstado.Disponible); 
            }
            reservas.delete(r);
        }
       }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        BuscarReservas dialog = new BuscarReservas(null, true);
        dialog.setList(reservas);
        dialog.setVisible(true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            Reserva seleccionado = dialog.getReservaSeleccionada();
            if (seleccionado != null) {
                reserva = seleccionado;
                mostrarDatos();
            }
        }});
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JFormattedTextField txtFechaFin;
    private javax.swing.JFormattedTextField txtFechaInicio;
    private javax.swing.JTextField txtVehiculo;
    // End of variables declaration//GEN-END:variables
}