/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Guis;

import PersonaCliente.Cliente;
import PersonaCliente.ClienteArrayList;
import Reservas.Reserva;
import Reservas.ReservasQueue;
import Utils.UtilDate;
import Utils.UtilGui;
import Vehiculos.VehiculoHashMap;
import Vehiculos.Vehiculo;
import Vehiculos.EnumEstado;
import java.time.LocalDate;
/**
 *
 * @author Braya
 */
public class FrmGestionReservas extends javax.swing.JInternalFrame {
    private ClienteArrayList clientes;
    private VehiculoHashMap vehiculos;
    private ReservasQueue reservas;
    private Reserva reserva;
    /**
     * Creates new form Gestion_Reservas
     */
    public FrmGestionReservas() {
        initComponents();
        this.setClosable(true);      // Activa la "X" para cerrar
        this.setResizable(false);
        this.setIconifiable(true);
        reservas = ReservasQueue.getInstance();
        vehiculos = VehiculoHashMap.getInstance();
        clientes =  ClienteArrayList.getInstance();
    }
    

    private boolean estaDisponible(String placa, LocalDate inicio, LocalDate fin) {
        for (Reserva r : reservas.getQueue()) {
            if (r.getPlacaVehiculo().equals(placa) && r.hayConflictoDeFecha(inicio, fin)) {
                return false;
            }
        }
        return true;
    }
    
    private void mostrarDatos() {
        txtCliente.setText(reserva.getCedulaCliente());
        txtFechaFin.setText(UtilDate.toString(reserva.getFechaFin()));
        txtFechaInicio.setText(UtilDate.toString(reserva.getFechaInicio()));
        txtVehiculo.setText(reserva.getPlacaVehiculo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtVehiculo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        txtFechaInicio = new javax.swing.JFormattedTextField();
        txtFechaFin = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(0, 153, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrear.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 38, 123, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Vehiculo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 113, 105, -1));

        txtCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 76, 125, -1));

        txtVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 157, 113, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Fecha de Inicio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 38, 166, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Fecha de Fin");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 38, 160, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Gestion De Reservas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 0, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        txtFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtFechaInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 76, 166, -1));

        txtFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtFechaFin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 76, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        if (txtCliente.getText().isBlank() || txtFechaInicio.getText().isBlank() || txtFechaFin.getText().isBlank() || txtVehiculo.getText().isBlank()) {
            UtilGui.enseñarMensaje(rootPane, "Faltan Datos", "Error");
            return;
        }

        if (clientes.find(txtCliente.getText()) == null) {
            UtilGui.enseñarMensaje(rootPane,"Cliente no registrado"," Error");
             return;
        }
        if (UtilDate.formatoFecha(txtFechaInicio.getText()).isBefore(LocalDate.now())) {
            UtilGui.enseñarMensaje(rootPane, "La fecha de inicio no puede ser menor a la actual","Error") ;
             return;
        }
        if (UtilDate.formatoFecha(txtFechaFin.getText()).isBefore(UtilDate.formatoFecha(txtFechaInicio.getText()))) {
             UtilGui.enseñarMensaje(rootPane," La fecha de finalización debe ser posterior a la de inicio", "Error") ;
              return;
        }
        if (UtilDate.formatoFecha(txtFechaInicio.getText()).plusDays(30).isBefore(UtilDate.formatoFecha(txtFechaFin.getText()))) {
            UtilGui.enseñarMensaje(rootPane," No se permiten reservas mayores a 30 días", "Error") ;
            return;
        }
        if (vehiculos.find(txtVehiculo.getText()) == null) {
            UtilGui.enseñarMensaje(rootPane,"Vehiculo no registrado"," Error");
             return;
        }
        
        Boolean disponible = estaDisponible(txtVehiculo.getText(),UtilDate.formatoFecha(txtFechaInicio.getText()),UtilDate.formatoFecha(txtFechaFin.getText()));
        
        if (disponible == false) {
           UtilGui.enseñarMensaje(rootPane,"️ El vehiculo seleccionado no esta disponible", "Error")  ;
           return;
        }

        Reserva nueva = new Reserva(txtCliente.getText() ,txtVehiculo.getText() , UtilDate.formatoFecha(txtFechaInicio.getText()) , UtilDate.formatoFecha(txtFechaFin.getText()));
        Vehiculo resultado = vehiculos.find(txtVehiculo.getText());
        resultado.setEstado(EnumEstado.Alquilado);

        reservas.add(nueva);        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (txtCliente.getText().isBlank() || txtFechaInicio.getText().isBlank() || txtFechaFin.getText().isBlank() || txtVehiculo.getText().isBlank()) {
            UtilGui.enseñarMensaje(rootPane, "Faltan Datos", "Error");
            return;
        }
        for (Reserva r : reservas.getQueue()) {
           r.confirmar();
       }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       boolean modificada = false;

    if (txtCliente.getText().isBlank() || txtFechaInicio.getText().isBlank() ||
        txtFechaFin.getText().isBlank() || txtVehiculo.getText().isBlank()) {
        UtilGui.enseñarMensaje(rootPane, "Faltan Datos", "Error");
        return;
    }

    String cedula = txtCliente.getText();
    String nuevaPlaca = txtVehiculo.getText();

    for (Reserva r : reservas.getQueue()) {
            if (r.getCedulaCliente().equals(cedula) && !r.isConfirmada()) {
                Vehiculo nuevoVehiculo = vehiculos.find(nuevaPlaca);
                if (nuevoVehiculo == null) {
                    UtilGui.enseñarMensaje(rootPane, "Vehículo no registrado", "Error");
                    return;
                }

                if (nuevoVehiculo.getEstado() != EnumEstado.Disponible) {
                    UtilGui.enseñarMensaje(rootPane, "Vehículo no disponible", "Error");
                    return;
                }

                if (!estaDisponible(nuevaPlaca, r.getFechaInicio(), r.getFechaFin())) {
                    UtilGui.enseñarMensaje(rootPane, "Vehículo ocupado en ese rango de fechas", "Error");
                    return;
                }

                Vehiculo anteriorVehiculo = vehiculos.find(r.getPlacaVehiculo());
                if (anteriorVehiculo != null) {
                    anteriorVehiculo.setEstado(EnumEstado.Disponible);
                }

                r.setPlacaVehiculo(nuevaPlaca);
                nuevoVehiculo.setEstado(EnumEstado.Alquilado);

                UtilGui.enseñarMensaje(rootPane, "Reserva modificada", "Info");
                modificada = true;
                break;
            }
           if (!modificada) {
            UtilGui.enseñarMensaje(rootPane, "Reserva no encontrada o ya confirmada", "Error");
           }


        }

       

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       if (txtCliente.getText().isBlank() || txtFechaInicio.getText().isBlank() || txtFechaFin.getText().isBlank() || txtVehiculo.getText().isBlank()) {
            UtilGui.enseñarMensaje(rootPane, "Faltan Datos", "Error");
            return;
        }
        for (Reserva r : reservas.getQueue()) {
           if (r.getCedulaCliente().equals(txtCliente.getText()) && r.getPlacaVehiculo().equals(txtVehiculo.getText())) {
            Vehiculo v = vehiculos.find(txtVehiculo.getText());
            if (v != null) {
                v.setEstado(EnumEstado.Disponible); 
            }
            reservas.delete(r);
        }
       }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        BuscarReservas dialog = new BuscarReservas(null, true);
        dialog.setList(reservas);
        dialog.setVisible(true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            Reserva seleccionado = dialog.getReservaSeleccionada();
            if (seleccionado != null) {
                reserva = seleccionado;
                mostrarDatos();
            }
        }});
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JFormattedTextField txtFechaFin;
    private javax.swing.JFormattedTextField txtFechaInicio;
    private javax.swing.JTextField txtVehiculo;
    // End of variables declaration//GEN-END:variables
}