/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Guis;


import java.awt.Font;
import java.awt.Image;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JMenu;
import javax.swing.Timer;

/**
 *
 * @author Braya
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
    private Timer timer;
    private int frame = 1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName());

    /**
     * Creates new form Menu_Principal
     */
    public FrmMenuPrincipal() {
        initComponents();
        iniciarAnimacion();
        
        // Centrar al iniciar
        centrarComponentes();
        centrarMenus();

        lblCarro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarro.setVerticalAlignment(javax.swing.SwingConstants.CENTER);

        // Recentrar cada vez que cambie el tamaño del DesktopPane
        jDesktopPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                centrarComponentes();
            }
        });

        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                centrarLabelsAbajo();
            }
        });
    }
    
    private void centrarMenus() {
        jMenuBar1.removeAll();
        // Centrado + espacios entre menús
        jMenuBar1.add(Box.createHorizontalGlue());
        jMenuBar1.add(mnbGestionClientes);
        jMenuBar1.add(Box.createHorizontalStrut(115));
        jMenuBar1.add(mnbGestionVehiculos);
        jMenuBar1.add(Box.createHorizontalStrut(115));
        jMenuBar1.add(mnbGestionEmpleados);
        jMenuBar1.add(Box.createHorizontalStrut(115));
        jMenuBar1.add(mnbGestionReservas);
        jMenuBar1.add(Box.createHorizontalStrut(115));
        jMenuBar1.add(mnbGestionAlquiler);
        jMenuBar1.add(Box.createHorizontalGlue());

        jMenuBar1.revalidate();
        jMenuBar1.repaint();
    }
    
    private void iniciarAnimacion() {
        timer = new javax.swing.Timer(1800, e -> animarCarro());
        timer.start(); 
    }

    private void animarCarro() {
        String ruta = "/Imagenes/carro" + frame + ".png";
        java.net.URL imgURL = getClass().getResource(ruta);
        if (imgURL != null) {
            ImageIcon icon = new ImageIcon(imgURL);
            lblCarro.setIcon(icon);
        }
        frame++;
        if (frame > 4) frame = 1;
    }
    
    public void centrarComponentes() {
        if (lblTitulo != null && lblCarro != null) {
            // Centrar título en la parte superior
            int xTitulo = (jDesktopPane1.getWidth() - lblTitulo.getPreferredSize().width) / 2;
            lblTitulo.setLocation(xTitulo, 20);

            // Centrar carro en el medio del DesktopPane
            int xCarro = (jDesktopPane1.getWidth() - lblCarro.getPreferredSize().width) / 2;
            int yCarro = (jDesktopPane1.getHeight() - lblCarro.getPreferredSize().height) / 2;
            lblCarro.setLocation(xCarro, yCarro);
        }
    }
    
    private void centrarLabelsAbajo() {
        int anchoPane = jDesktopPane1.getWidth();
        int altoPane = jDesktopPane1.getHeight();

        int espacio = 20; // espacio entre labels

        // Medidas de los labels
        int ancho1 = jLabel1.getWidth();
        int ancho2 = jLabel2.getWidth();

        int alto = Math.max(jLabel1.getHeight(), jLabel2.getHeight());

        // Calcular posiciones para centrarlos en bloque
        int anchoTotal = ancho1 + espacio + ancho2;
        int xInicio = (anchoPane - anchoTotal) / 2;
        int yPos = altoPane - alto - 20; // 20 px arriba del borde inferior

        // Ubicar cada label
        jLabel1.setLocation(xInicio, yPos);
        jLabel2.setLocation(xInicio + ancho1 + espacio, yPos);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblCarro = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnbGestionClientes = new javax.swing.JMenu();
        itmGestionClientes = new javax.swing.JMenuItem();
        mnbGestionVehiculos = new javax.swing.JMenu();
        itmGestionVehiculo = new javax.swing.JMenuItem();
        mnbGestionEmpleados = new javax.swing.JMenu();
        itmGestionEmpleados = new javax.swing.JMenuItem();
        mnbGestionReservas = new javax.swing.JMenu();
        itmGestionReservas = new javax.swing.JMenuItem();
        mnbGestionAlquiler = new javax.swing.JMenu();
        itmGestionAlquiler = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carro3.png"))); // NOI18N
        lblCarro.setMaximumSize(new java.awt.Dimension(700, 500));
        lblCarro.setPreferredSize(new java.awt.Dimension(600, 400));
        jDesktopPane1.add(lblCarro);
        lblCarro.setBounds(20, 40, 600, 310);

        lblTitulo.setBackground(new java.awt.Color(51, 51, 51));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Sistema de Gestion de Vehiculos");
        jDesktopPane1.add(lblTitulo);
        lblTitulo.setBounds(100, 20, 530, 48);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MotorCore");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(10, 320, 150, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Encontranos en nuestras tiendas y redes sociales, Somos grupo MotorCore");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(140, 320, 770, 30);

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        mnbGestionClientes.setText("Gestion Clientes");
        mnbGestionClientes.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        itmGestionClientes.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        itmGestionClientes.setText("Abrir Gestion Clientes");
        itmGestionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmGestionClientesActionPerformed(evt);
            }
        });
        mnbGestionClientes.add(itmGestionClientes);

        jMenuBar1.add(mnbGestionClientes);

        mnbGestionVehiculos.setText("Gestion Vehiculos");
        mnbGestionVehiculos.setToolTipText("");
        mnbGestionVehiculos.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        itmGestionVehiculo.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        itmGestionVehiculo.setText("Abrir Gestion Vehiculos");
        itmGestionVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmGestionVehiculoActionPerformed(evt);
            }
        });
        mnbGestionVehiculos.add(itmGestionVehiculo);

        jMenuBar1.add(mnbGestionVehiculos);

        mnbGestionEmpleados.setText("Gestion Empleados");
        mnbGestionEmpleados.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        itmGestionEmpleados.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        itmGestionEmpleados.setText("Abrir Gestion Empleados");
        itmGestionEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmGestionEmpleadosActionPerformed(evt);
            }
        });
        mnbGestionEmpleados.add(itmGestionEmpleados);

        jMenuBar1.add(mnbGestionEmpleados);

        mnbGestionReservas.setText("Gestion Reservas");
        mnbGestionReservas.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        itmGestionReservas.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        itmGestionReservas.setText("Abrir Gestion Reservas");
        itmGestionReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmGestionReservasActionPerformed(evt);
            }
        });
        mnbGestionReservas.add(itmGestionReservas);

        jMenuBar1.add(mnbGestionReservas);

        mnbGestionAlquiler.setText("Gestion Alquiler");
        mnbGestionAlquiler.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        itmGestionAlquiler.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        itmGestionAlquiler.setText("Abrir Gestion Alquiler");
        itmGestionAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmGestionAlquilerActionPerformed(evt);
            }
        });
        mnbGestionAlquiler.add(itmGestionAlquiler);

        jMenuBar1.add(mnbGestionAlquiler);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmGestionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmGestionClientesActionPerformed
        FrmGestionClientes ventanaCliente = new FrmGestionClientes();
        jDesktopPane1.add(ventanaCliente);
        ventanaCliente.setVisible(true);
    }//GEN-LAST:event_itmGestionClientesActionPerformed

    private void itmGestionVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmGestionVehiculoActionPerformed
        FrmGestionVehiculos ventanaVehiculo = new FrmGestionVehiculos();
        jDesktopPane1.add(ventanaVehiculo);
        ventanaVehiculo.setVisible(true);
    }//GEN-LAST:event_itmGestionVehiculoActionPerformed

    private void itmGestionEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmGestionEmpleadosActionPerformed
        FrmGestionEmpleados ventanaEmpleado = new FrmGestionEmpleados();
        jDesktopPane1.add(ventanaEmpleado);
        ventanaEmpleado.setVisible(true);
    }//GEN-LAST:event_itmGestionEmpleadosActionPerformed

    private void itmGestionReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmGestionReservasActionPerformed
        FrmGestionReservas ventanaReservas = new FrmGestionReservas();
        jDesktopPane1.add(ventanaReservas);
        ventanaReservas.setVisible(true);
    }//GEN-LAST:event_itmGestionReservasActionPerformed

    private void itmGestionAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmGestionAlquilerActionPerformed
        FrmGestionAlquiler ventanaAlquiler = new FrmGestionAlquiler();
        jDesktopPane1.add(ventanaAlquiler);
        ventanaAlquiler.setVisible(true);
    }//GEN-LAST:event_itmGestionAlquilerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmGestionAlquiler;
    private javax.swing.JMenuItem itmGestionClientes;
    private javax.swing.JMenuItem itmGestionEmpleados;
    private javax.swing.JMenuItem itmGestionReservas;
    private javax.swing.JMenuItem itmGestionVehiculo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblCarro;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenu mnbGestionAlquiler;
    private javax.swing.JMenu mnbGestionClientes;
    private javax.swing.JMenu mnbGestionEmpleados;
    private javax.swing.JMenu mnbGestionReservas;
    private javax.swing.JMenu mnbGestionVehiculos;
    // End of variables declaration//GEN-END:variables
}
